name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  workflow_dispatch: # Allows manual triggering of the workflow from the GitHub Actions tab

jobs:
  build-and-run:
    runs-on: ubuntu-latest # Uses a fresh Ubuntu virtual machine for each job

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Updated to v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3 # Using dedicated action for Docker login
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Recommended for modern Docker builds

      - name: Get current date for image tag
        id: date
        run: echo "DATE=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5 # Using dedicated action for build & push
        with:
          context: .
          push: true
          # IMPORTANT: Replace YOUR_DOCKERHUB_USERNAME with your actual DockerHub username.
          tags: ${{ secrets.DOCKER_USERNAME }}/nodejs-app:${{ steps.date.outputs.DATE }},${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest

      - name: Run Docker container (for verification on runner)
        run: |
          echo "Stopping and removing any previous containers on this temporary runner..."
          docker stop nodejs-app-container || true
          docker rm nodejs-app-container || true

          echo "Running container from image ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest"
          docker run -d -p 3000:3000 --name nodejs-app-container ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest

          echo "Container started. Waiting a few seconds for the app to initialize..."
          sleep 5

          echo "Verifying application access via curl (http://localhost:3000)..."
          curl -v http://localhost:3000 || true

          echo "Viewing container logs..."
          docker logs nodejs-app-container